[build]
  command = "pnpm run build:netlify"
  publish = "netlify-dist"

[build.environment]
  NODE_VERSION = "22.13.0"
  PNPM_VERSION = "10.6.5"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
